# locust file generated by wtg-seal (release {})
# See https://github.com/mchoji/wtg-seal for more information

from locust import HttpUser, TaskSet, task
from scipy.stats import pareto
import locust.stats
locust.stats.CSV_STATS_INTERVAL_SEC = 5


class UserTestSet(TaskSet):
    @task(0)
    def getdoc0(self):
        self.client.get("/1.txt", name="doc#0")

    @task(3)
    def getdoc1(self):
        self.client.get("/1.txt", name="doc#1")
        self.client.get("/2.txt", name="doc#1")
        self.client.get("/3.txt", name="doc#1")

    @task(0)
    def getdoc2(self):
        self.client.get("/4.txt", name="doc#2")
        self.client.get("/5.txt", name="doc#2")
        self.client.get("/6.txt", name="doc#2")
        self.client.get("/7.txt", name="doc#2")
        self.client.get("/8.txt", name="doc#2")
        self.client.get("/9.txt", name="doc#2")
        self.client.get("/10.txt", name="doc#2")


class WebUserLocust(HttpUser):
    weight = 2
    tasks = [UserTestSet]
    pareto_obj = pareto(b=1.4, scale=1)
    pareto_obj.random_state = 2

    def wait_time(self):
        return self.pareto_obj.rvs()
